version: "3.8"

services:
  traefik:
    image: "traefik:v2.6.6"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--log.filePath:/opt/traefik/log/traefik.log"
      - "--accesslog=true"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.filepath=/opt/traefik/log/access.log"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.custom.address=:8080"
    ports:
      - "80:80"
      - "443:443"
      - "10.200.3.5:8080:8080"
    networks:
      - webaccess
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/traefik/log/:/log/"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    restart: unless-stopped
    networks:
      - webaccess
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.mobilab.cloud`)"

networks:
  webaccess:
    external: true
