version: "3.8"

services:
  traefik:
    image: "traefik:v2.6.6"
    container_name: "traefik"
    restart: always
    networks:
      - webaccess
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONTAINERPATH}/traefik.yml:/traefik.yml:ro"
      - "${CONTAINERPATH}/acme.json:/acme.json:rw"
      - "${CONTAINERPATH}/config.yml:/config.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mobilab.cloud`)"
      - "traefik.http.routers.traefik.middlewares=SecHeader@file"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  webaccess:
    external: true
