version: "3.8"

services:
  dockerproxy:
    image: "tecnativa/docker-socket-proxy"
    container_name: "socket-proxy"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - CONTAINERS=1
    networks:
      - socket_proxy
    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    image: "traefik:v2.6.6"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - socket_proxy
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${CONTAINER_TRAEFIK_PATH}/traefik.yml:/traefik.yml:ro"
      - "${CONTAINER_TRAEFIK_PATH}/acme.json:/acme.json:rw"
      - "${CONTAINER_TRAEFIK_PATH}/config.yml:/config.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.mobilab.cloud`)"
      - "traefik.http.routers.traefik.middlewares=SecHeader@file"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.options=intermediate@file"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  portainer:
    image: "portainer/portainer-ce"
    container_name: "portainer"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${CONTAINER_PORTAINER_PATH}:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.mobilab.cloud`)"
      - "traefik.http.routers.portainer.middlewares=SecHeader@file"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.options=intermediate@file"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
  socket_proxy:
    external: true
